project_id = "hipolqjthriiwdzfxpdd"

[functions.scrape-website]
verify_jwt = true

[functions.generate-prompt-video]
verify_jwt = false

[functions.clone-video-style]
verify_jwt = false

[functions.generate-ugc-video] 
verify_jwt = false

[functions.create-explainer-video]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.generate-scenes]
verify_jwt = false

[functions.generate-scene-video]
verify_jwt = false

[functions.generate-video-with-audio]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false